<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HIJ-WS022" failures="1" tests="3" name="TestRunner.ForgetPasswordTest" time="26.272" errors="0" timestamp="2021-12-06T16:01:36 IST" skipped="0">
  <testcase classname="TestRunner.ForgetPasswordTest" name="runScenario" time="10.609">
    <failure message="expected [Email with instructions has been sent to you.] but found [Email not found.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Email with instructions has been sent to you.] but found [Email not found.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at StepDefination.ForgetPasswordSteps.a_message_of_recovery_link_successfully_send_should_be_displayed(ForgetPasswordSteps.java:52)
at âœ½.A message of recovery link successfully send should be displayed(file:///C:/Users/RISHU.Sharma/Downloads/TestDemo%20(3)/TestDemoNew/TestDemo/src/test/resources/AppFeatures/ForgetPassword.feature:12)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="TestRunner.ForgetPasswordTest" name="runScenario" time="7.180"/>
  <system-out/>
  <testcase classname="TestRunner.ForgetPasswordTest" name="runScenario" time="8.483"/>
  <system-out/>
</testsuite> <!-- TestRunner.ForgetPasswordTest -->
